sudo: false
addons:
  postgresql: "9.6"
services:
  - postgresql
language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database debloater_test;' -U postgres

