dist: trusty
sudo: true
addons:
  postgresql: "9.6"
language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler
before_script:
  - psql --version
  - psql -c 'create database debloater_test;' -U postgres

